
spring.application.name=wordweft-backend
server.port=8081

# MongoDB Configuration
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.data.mongodb.auto-index-creation=true

# App Properties
wordweft.app.jwtSecret=${JWT_TOKEN}
wordweft.app.jwtExpirationMs=${JWT_EXPIRY}
wordweft.app.googleClientId=${GOOGLE_CLIENT_ID}

# JSON Date Format Fix
spring.jackson.serialization.write-dates-as-timestamps=false

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=INFO

# Email Configuration (Google Apps Script Web App)
wordweft.email.apps-script-url=${GMAIL_APPS_SCRIPT_URL}

# Frontend URL (for password reset links)
wordweft.app.frontendUrl=${FRONTEND_HOST}

# ImageKit Configuration
imagekit.public-key=${IMAGEKIT_PUBLIC_KEY}
imagekit.private-key=${IMAGEKIT_PRIVATE_KEY}
imagekit.url-endpoint=https://ik.imagekit.io/wordweft/
