
spring.application.name=wordweft-backend
server.port=8081

# MongoDB Configuration
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.data.mongodb.auto-index-creation=true

# App Properties
wordweft.app.jwtSecret=${JWT_TOKEN}
wordweft.app.jwtExpirationMs=${JWT_EXPIRY}
wordweft.app.googleClientId=${GOOGLE_CLIENT_ID}

# JSON Date Format Fix
spring.jackson.serialization.write-dates-as-timestamps=false

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=INFO

# Gmail SMTP Configuration
spring.mail.host=${GMAIL_HOST}
spring.mail.port=${GMAIL_PORT}
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Frontend URL (for password reset links)
wordweft.app.frontendUrl=${FRONTEND_HOST}

